### ISSUE TITLE
Rescue Timeout error in multi geocoder

### ISSUE THREAD

**Issue by dpetersen** [collectiveidea/graticule#10]
A timeout during geocoding results in the following backtrace, as we discussed:

<pre>
rake aborted!
execution expired
/usr/lib/ruby/1.8/timeout.rb:60:in `open'
/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
/usr/lib/ruby/1.8/timeout.rb:93:in `timeout'
/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
/usr/lib/ruby/1.8/net/http.rb:542:in `start'
/usr/lib/ruby/1.8/open-uri.rb:242:in `open_http'
/usr/lib/ruby/1.8/open-uri.rb:616:in `buffer_open'
/usr/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
/usr/lib/ruby/1.8/open-uri.rb:162:in `catch'
/usr/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
/usr/lib/ruby/1.8/open-uri.rb:132:in `open_uri'
/usr/lib/ruby/1.8/open-uri.rb:518:in `open'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/base.rb:79:in `get'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/yahoo.rb:43:in `locate'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:45
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:44
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:69:in `call'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:69:in `result'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:180:in `detect'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:68:in `each'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:68:in `detect'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:68:in `result'
/home/hov/.bundle/ruby/1.8/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/multi.rb:54:in `locate'
/home/hov/.bundle/ruby/1.8/gems/acts_as_geocodable-1.0.3/lib/acts_as_geocodable/geocode.rb:31:in `create_from_location'
/home/hov/.bundle/ruby/1.8/gems/acts_as_geocodable-1.0.3/lib/acts_as_geocodable/geocode.rb:27:in `find_or_create_by_location'
/home/hov/.bundle/ruby/1.8/gems/acts_as_geocodable-1.0.3/lib/acts_as_geocodable.rb:262:in `attach_geocode'
/data/hov/releases/20100408191329/lib/tasks/geocode.rake:5:in `send'
/data/hov/releases/20100408191329/lib/tasks/geocode.rake:5
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/batches.rb:26:in `find_each'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/batches.rb:26:in `each'
</pre>

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-open it by May 17, 2017. Thanks!
