### ISSUE TITLE
Error with Ruby 1.9.2pre3 & Rails 3 beta4

### ISSUE THREAD

**Issue by manuelmeurer** [collectiveidea/graticule#11]
I'm getting the following error when trying to use Graticule with Ruby 1.9.2pre3 & Rails 3 beta4:

/Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/google.rb:57:in `<class:Placemark>': undefined method`with_options' for Graticule::Geocoder::Google::Placemark:Class (NoMethodError)
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/google.rb:48:in `<class:Google>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/google.rb:12:in`module:Geocoder'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/google.rb:2:in `<module:Graticule>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule/geocoder/google.rb:1:in`<top (required)>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule.rb:11:in `require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/graticule-1.0.0.pre2/lib/graticule.rb:11:in`<top (required)>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:46:in `require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:46:in`block (2 levels) in require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:41:in `each'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:41:in`block in require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:40:in `each'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler/runtime.rb:40:in`require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/bundler-0.9.26/lib/bundler.rb:89:in `gem_require'
    from /Users/foo/apps/bar/config/application.rb:7:in`<top (required)>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/railties-3.0.0.beta4/lib/rails/commands.rb:28:in `require'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/railties-3.0.0.beta4/lib/rails/commands.rb:28:in`block in <top (required)>'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/railties-3.0.0.beta4/lib/rails/commands.rb:27:in `tap'
    from /Users/foo/.rvm/gems/ruby-1.9.2-preview3/gems/railties-3.0.0.beta4/lib/rails/commands.rb:27:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

First I though "with_options" had been removed in Rails 3 but it seems to still be there (at least in beta3): http://apidock.com/rails/v3.0.0.beta3/Object/with_options

Any idea what's going on?

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-open it by May 17, 2017. Thanks!
