### ISSUE TITLE
missing ssl for google map api

### ISSUE THREAD

**Issue by kbaum** [collectiveidea/graticule#31]
I made the following request:

``` ruby
location = Geocode.geocoder.locate "61 East 9th Street, Holland, MI"
```

And i got the following error message:

```
"{\n   \"error_message\" : \"Requests to this API must be over SSL.\",\n   \"results\" : [],\n   \"status\" : \"REQUEST_DENIED\"\n}\n"
```

I modified graticule to make requests with https and now i am getting:

```
"error_message\" : \"This site is not authorized to use this API key.\",\n   \"results\" : [],\n   \"status\" : \"REQUEST_DENIED\"\n}
```

I am using graticule 2.3.0.

thx!

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-open it by May 17, 2017. Thanks!
