### ISSUE TITLE
Add support for geocoders that return multiple results

### ISSUE THREAD

**Issue by bkeepers** [collectiveidea/graticule#8]
For the geocoders that support multiple results, we should modify the graticule API to allow all the results to be returned.

Some initial support for this was done [here](http://github.com/norman/graticule), but never got pulled in.

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-open it by May 17, 2017. Thanks!
